back_end_main:
    path: /
    defaults: { _controller: AppBundle:backend:index }

profile:
    path: profile
    defaults: { _controller: AppBundle:backend:profile }

users:
    path: users
    defaults: { _controller: AppBundle:backend:users }